replicaCount: 1

frontend:
  image: public.ecr.aws/y8u8k9s8/team4/istone:frontend-1.0
  port: 4200

backend:
  image: public.ecr.aws/y8u8k9s8/team4/istone:backend-1.0
  port: 8080

mysql:
  image: mysql:8.0
  rootPassword: password
  database: istdatabase
  user: user
  userPassword: userpassword
  port: 3306

service:
  frontend:
    type: ClusterIP
    port: 80
    targetPort: 4200
  backend:
    type: ClusterIP
    port: 80
    targetPort: 8080
  mysql:
    type: ClusterIP
    port: 3306

resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}
